# Exemption: allow this specific lead magnet to be downloaded by the public
[[redirects]]
  from = "/library/files/au-ransom-policy-explainer.pdf"
  to = "/library/files/au-ransom-policy-explainer.pdf"
  status = 200
  force = true

# Gate everything else in /library/files for public users
[[redirects]]
  from = "/library/files/*"
  to = "/signin"
  status = 302
  force = true
  conditions = { Role = ["public"] }

# Cache control for Library pages
[[headers]]
  for = "/library/*"
  [headers.values]
    Cache-Control = "private, max-age=0, no-store"

# Keep raw downloads out of search + caches
[[headers]]
  for = "/library/files/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "private, max-age=0, no-store"

# Stripe → Netlify Function endpoint
[[redirects]]
  from = "/stripe/webhook"
  to   = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true
